language: python
sudo: false
matrix:
  include:
  - python: 3.5
    env: TOXENV=lint
  - python: 2.7
    env: TOXENV=py27
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.6
    env: TOXENV=cover
cache:
  directories:
  - ${HOME}/.cache
install:
- pip install --upgrade tox
script:
- tox
